#!/usr/bin/env bash
# plan_dx9.md Phase D9-12 (D9-120): promotes the D9-A oracle scene corpus into a real CTest.
#
# Renders every checked-in scene (tools/xna-oracle/scenes/*.scene) through CNA's own real D3D9
# renderer (cna_oracle_render.exe) and diffs each result against the checked-in real XNA 4.0
# reference PNG (tools/xna-oracle/reference/*.png), at D9-A4's own tolerance=0 (exact match).
#
# Deliberately does NOT need the XNA Wine prefix (~/.wine-cna-xna40) at all -- only the D3D9 Wine
# prefix every other D3D9 CTest already needs, to run cna_oracle_render.exe itself. The reference
# PNGs were captured once, by hand, against the real XNA 4.0 runtime under Wine, and are checked
# into git -- this script's whole point is to keep validating against them WITHOUT re-running
# Wine+XNA every time. If a scene's own expected output ever needs to change (a new scene added,
# or a scene file's own content deliberately edited), the reference PNG must be regenerated by
# hand against the real XNA oracle (see tools/xna-oracle/README.md) and re-committed -- never
# edit a reference PNG any other way, and never widen this script's own tolerance to turn a red
# comparison green (D9-A4's own explicit warning, restated here).
#
# Usage: scripts/run-oracle-corpus-diff.sh <path-to-cna_oracle_render.exe>

set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

if [ $# -lt 1 ]; then
    echo "usage: $0 <path-to-cna_oracle_render.exe>" >&2
    exit 2
fi
CNA_ORACLE_RENDER_EXE="$1"

SCENES_DIR="$REPO_ROOT/tools/xna-oracle/scenes"
REFERENCE_DIR="$REPO_ROOT/tools/xna-oracle/reference"
WORK_DIR="$(mktemp -d)"
trap 'rm -rf "$WORK_DIR"' EXIT

TOTAL=0
FAILED=0

for scene in "$SCENES_DIR"/*.scene; do
    name="$(basename "$scene" .scene)"
    reference="$REFERENCE_DIR/$name.png"
    TOTAL=$((TOTAL + 1))

    if [ ! -f "$reference" ]; then
        echo "FAIL: $name -- no checked-in reference image at $reference"
        FAILED=$((FAILED + 1))
        continue
    fi

    out="$WORK_DIR/$name.png"
    if ! "$SCRIPT_DIR/run-wine-dxvk9.sh" "$CNA_ORACLE_RENDER_EXE" "$scene" "$out" \
            > "$WORK_DIR/$name.render.log" 2>&1; then
        echo "FAIL: $name -- cna_oracle_render.exe itself failed:"
        tail -20 "$WORK_DIR/$name.render.log"
        FAILED=$((FAILED + 1))
        continue
    fi

    if ! diffOutput=$(python3 "$SCRIPT_DIR/xna-diff.py" "$reference" "$out" --tolerance 0 2>&1); then
        echo "FAIL: $name -- $diffOutput"
        FAILED=$((FAILED + 1))
    else
        echo "PASS: $name -- $diffOutput"
    fi
done

PASSED=$((TOTAL - FAILED))
echo "=== $PASSED/$TOTAL scenes match real XNA 4.0 exactly (checked-in reference images) ==="

if [ "$FAILED" -eq 0 ]; then
    exit 0
else
    exit 1
fi
