// SPDX-License-Identifier: MIT
// Copyright (c) Robert Vokac and contributors
// Portions based on .NET runtime API (MIT License, Copyright .NET Foundation and Contributors)
#pragma once
#include "System/Attribute.hpp"

namespace System::Runtime::CompilerServices {

    /**
     * @brief Marks a type or member as having been generated by the compiler.
     *
     * C++ counterpart of .NET System.Runtime.CompilerServices.CompilerGeneratedAttribute. Has no
     * runtime behavior in either language — a pure marker. Present here as an inert data-holding
     * type for source-level fidelity, matching the other attribute ports in this codebase.
     */
    class CompilerGeneratedAttribute : public System::Attribute {
    public:
        CompilerGeneratedAttribute() = default;
    };

} // namespace System::Runtime::CompilerServices
