// SPDX-License-Identifier: MS-PL
//
// plan_xnb.md XNB-28/29/30B: unit tests for LzxDecoder and DecompressXnbPayload, verified
// against real, externally-produced LZX-compressed .xnb fixtures (never hand-crafted -- valid
// LZX-compressed bytes cannot be authored by hand).

#include <algorithm>
#include <fstream>
#include <gtest/gtest.h>
#include <sstream>

#include "CNA/Internal/Xnb/LzxDecoder.hpp"
#include "CNA/Internal/Xnb/XnbDecompression.hpp"
#include "CNA/Internal/Xnb/XnbHeader.hpp"
#include "CNA/Internal/Xnb/XnbTypeReaderTable.hpp"
#include "Microsoft/Xna/Framework/Content/ContentLoadException.hpp"
#include "System/IO/BinaryReader.hpp"
#include "System/IO/MemoryStream.hpp"

using Microsoft::Xna::Framework::Content::ContentLoadException;

namespace
{
    std::string ReadWholeFile(const std::string& path)
    {
        std::ifstream file(path, std::ios::binary);
        if (!file.is_open()) return {};
        std::ostringstream ss;
        ss << file.rdbuf();
        return ss.str();
    }
}

TEST(LzxDecoderTest, RealCompressedMonoGameFixtureDecompressesToAValidTypeReaderTable)
{
    // Real, externally-produced LZX-compressed fixture (MonoGame's own
    // Tests/Interactive/MacOS/SoundTest/Content/Explosion.xnb, a compiled SoundEffect),
    // vendored at tests/assets/xnb/monogame/windows/lzx/. Never generated by CNA.
    const std::string fileBytes = ReadWholeFile("tests/assets/xnb/monogame/windows/lzx/Explosion.xnb");
    ASSERT_FALSE(fileBytes.empty()) << "Real compressed .xnb fixture not found relative to CWD";

    System::IO::MemoryStream headerStream(
        reinterpret_cast<const uint8_t*>(fileBytes.data()), (int32_t)fileBytes.size());
    System::IO::BinaryReader headerReader(&headerStream, true);
    const auto header = CNA::Internal::Xnb::ParseXnbHeader(headerReader, "Explosion.xnb");

    ASSERT_EQ(header.compression, CNA::Internal::Xnb::XnbCompression::Lzx);
    EXPECT_EQ(header.version, 5);
    EXPECT_EQ(header.platform, 'w');

    System::IO::MemoryStream sizeStream(
        reinterpret_cast<const uint8_t*>(fileBytes.data()) + 10, 4);
    System::IO::BinaryReader sizeReader(&sizeStream, true);
    const int32_t decompressedSize = sizeReader.ReadInt32();
    const int32_t compressedSize = header.totalLength - 14;

    const auto decompressed = CNA::Internal::Xnb::DecompressXnbPayload(
        reinterpret_cast<const uint8_t*>(fileBytes.data()) + 14,
        compressedSize, decompressedSize, "Explosion.xnb");

    ASSERT_EQ(decompressed.size(), static_cast<std::size_t>(decompressedSize));

    // If decompression produced correct bytes, the very first thing in the decompressed stream
    // is a real, well-formed type-reader table -- parsing it should succeed and name a real FNA
    // reader (a corrupted decompression would almost certainly fail this parse or produce
    // nonsense instead of a real, recognizable reader name).
    System::IO::MemoryStream bodyStream(decompressed.data(), (int32_t)decompressed.size());
    System::IO::BinaryReader bodyReader(&bodyStream, true);
    const auto table = CNA::Internal::Xnb::ParseXnbTypeReaderTable(bodyReader, "Explosion.xnb");

    // A malformed decompression would almost certainly not produce a well-formed table at all
    // (the 7-bit-encoded count/string-length reads would desync into nonsense and either throw
    // or produce garbage). It did not: exactly one entry, naming a real, existing FNA reader.
    ASSERT_EQ(table.size(), 1u);
    EXPECT_EQ(table[0].normalizedName, "Microsoft.Xna.Framework.Content.Texture2DReader");
    EXPECT_EQ(table[0].version, 0);

    // Stronger correctness check: read the Texture2DReader-shaped fields that follow and verify
    // an arithmetic identity holds *across two independently-read parts of the decompressed
    // stream* (width/height, read early, vs. the level-0 byte count, read much later after many
    // more decompressed bytes). A subtly wrong LZX decompression could not produce this exact
    // relationship by chance.
    const int32_t sharedCount = bodyReader.Read7BitEncodedInt();
    const int32_t rootIndex = bodyReader.Read7BitEncodedInt();
    const int32_t surfaceFormat = bodyReader.ReadInt32();
    const int32_t width = bodyReader.ReadInt32();
    const int32_t height = bodyReader.ReadInt32();
    const int32_t mipCount = bodyReader.ReadInt32();
    const int32_t level0Bytes = bodyReader.ReadInt32();

    EXPECT_EQ(sharedCount, 0);
    EXPECT_EQ(rootIndex, 1);
    EXPECT_EQ(surfaceFormat, 0); // SurfaceFormat.Color
    EXPECT_EQ(width, 64);
    EXPECT_EQ(height, 64);
    EXPECT_EQ(mipCount, 1);
    EXPECT_EQ(level0Bytes, width * height * 4);
}

TEST(LzxDecoderTest, MultiBlockRealFixtureDecompressesCorrectlyAcrossBlockBoundary)
{
    // Real, externally-produced LZX-compressed fixture (MonoGame's own
    // Tests/Interactive/MacOS/TextureScaleColorTest/Content/FontCalibri14.xnb, a compiled
    // SpriteFont) whose decompressed size (44032 bytes) spans more than one 32KB LZX block --
    // genuinely exercises the block-framing loop's multi-block state persistence, not just a
    // single Decompress() call.
    const std::string fileBytes = ReadWholeFile("tests/assets/xnb/monogame/windows/lzx/FontCalibri14.xnb");
    ASSERT_FALSE(fileBytes.empty()) << "Real compressed .xnb fixture not found relative to CWD";

    System::IO::MemoryStream headerStream(
        reinterpret_cast<const uint8_t*>(fileBytes.data()), (int32_t)fileBytes.size());
    System::IO::BinaryReader headerReader(&headerStream, true);
    const auto header = CNA::Internal::Xnb::ParseXnbHeader(headerReader, "FontCalibri14.xnb");
    ASSERT_EQ(header.compression, CNA::Internal::Xnb::XnbCompression::Lzx);

    System::IO::MemoryStream sizeStream(reinterpret_cast<const uint8_t*>(fileBytes.data()) + 10, 4);
    System::IO::BinaryReader sizeReader(&sizeStream, true);
    const int32_t decompressedSize = sizeReader.ReadInt32();
    const int32_t compressedSize = header.totalLength - 14;

    ASSERT_GT(decompressedSize, 32768) << "fixture no longer spans multiple LZX blocks";

    const auto decompressed = CNA::Internal::Xnb::DecompressXnbPayload(
        reinterpret_cast<const uint8_t*>(fileBytes.data()) + 14,
        compressedSize, decompressedSize, "FontCalibri14.xnb");

    ASSERT_EQ(decompressed.size(), static_cast<std::size_t>(decompressedSize));

    System::IO::MemoryStream bodyStream(decompressed.data(), (int32_t)decompressed.size());
    System::IO::BinaryReader bodyReader(&bodyStream, true);
    const auto table = CNA::Internal::Xnb::ParseXnbTypeReaderTable(bodyReader, "FontCalibri14.xnb");

    // A real SpriteFont's type-reader table names exactly this reader set (matching FNA's own
    // SpriteFontReader.cs structure: a glyph-atlas Texture2D, glyph/cropping Rectangle lists,
    // a character list, and a kerning-triple Vector3 list) -- including correctly-parsed nested
    // generic names (XNB-13) recovered from real decompressed bytes for the first time (the
    // earlier uncompressed fixture's reader was non-generic). A wrong decompression could not
    // produce this exact, semantically sensible structure.
    std::vector<std::string> names;
    names.reserve(table.size());
    for (const auto& e : table) names.push_back(e.normalizedName);
    std::sort(names.begin(), names.end());

    std::vector<std::string> expected{
        "Microsoft.Xna.Framework.Content.CharReader",
        "Microsoft.Xna.Framework.Content.ListReader`1[[Microsoft.Xna.Framework.Rectangle]]",
        "Microsoft.Xna.Framework.Content.ListReader`1[[Microsoft.Xna.Framework.Vector3]]",
        "Microsoft.Xna.Framework.Content.ListReader`1[[System.Char]]",
        "Microsoft.Xna.Framework.Content.RectangleReader",
        "Microsoft.Xna.Framework.Content.SpriteFontReader",
        "Microsoft.Xna.Framework.Content.Texture2DReader",
        "Microsoft.Xna.Framework.Content.Vector3Reader"};
    std::sort(expected.begin(), expected.end());

    EXPECT_EQ(names, expected);
}

TEST(LzxDecoderTest, WrongDecompressedSizeThrowsContentLoadException)
{
    const std::string fileBytes = ReadWholeFile("tests/assets/xnb/monogame/windows/lzx/Explosion.xnb");
    ASSERT_FALSE(fileBytes.empty());

    System::IO::MemoryStream headerStream(
        reinterpret_cast<const uint8_t*>(fileBytes.data()), (int32_t)fileBytes.size());
    System::IO::BinaryReader headerReader(&headerStream, true);
    const auto header = CNA::Internal::Xnb::ParseXnbHeader(headerReader, "Explosion.xnb");
    const int32_t compressedSize = header.totalLength - 14;

    EXPECT_THROW(
        CNA::Internal::Xnb::DecompressXnbPayload(
            reinterpret_cast<const uint8_t*>(fileBytes.data()) + 14,
            compressedSize, /*decompressedSize=*/999999, "Explosion.xnb"),
        ContentLoadException);
}

TEST(LzxDecoderTest, OversizedDecompressedSizeThrowsContentLoadExceptionBeforeAllocating)
{
    const std::vector<uint8_t> bytes{0, 0, 0, 0};
    EXPECT_THROW(
        CNA::Internal::Xnb::DecompressXnbPayload(bytes.data(), 4, 0x7FFFFFFF, "test.xnb"),
        ContentLoadException);
}

TEST(LzxDecoderTest, UnsupportedWindowSizeThrows)
{
    EXPECT_THROW(CNA::Internal::Xnb::LzxDecoder(14), CNA::Internal::Xnb::UnsupportedLzxWindowSizeRange);
    EXPECT_THROW(CNA::Internal::Xnb::LzxDecoder(22), CNA::Internal::Xnb::UnsupportedLzxWindowSizeRange);
    EXPECT_NO_THROW(CNA::Internal::Xnb::LzxDecoder(16));
}
