// SPDX-License-Identifier: MS-PL
//
// plan_xnb.md XNB-11: unit tests for ParseXnbHeader().

#include <gtest/gtest.h>
#include <vector>

#include "CNA/Internal/Xnb/XnbHeader.hpp"
#include "Microsoft/Xna/Framework/Content/ContentLoadException.hpp"
#include "System/IO/BinaryReader.hpp"
#include "System/IO/EndOfStreamException.hpp"
#include "System/IO/MemoryStream.hpp"

using CNA::Internal::Xnb::ParseXnbHeader;
using CNA::Internal::Xnb::XnbCompression;
using CNA::Internal::Xnb::XnbHeader;
using Microsoft::Xna::Framework::Content::ContentLoadException;

namespace
{
    XnbHeader ParseBytes(const std::vector<uint8_t>& bytes)
    {
        System::IO::MemoryStream ms(bytes.data(), static_cast<int32_t>(bytes.size()));
        System::IO::BinaryReader reader(&ms, true);
        return ParseXnbHeader(reader, "test.xnb");
    }
}

TEST(XnbHeaderTest, RealMonoGameFixtureHeaderParsesCorrectly)
{
    // First 10 bytes of MonoGame's own Tests/Assets/Textures/white-1.xnb (191-byte file),
    // produced by real MonoGame content-pipeline tooling, never generated by CNA.
    const std::vector<uint8_t> bytes{
        'X', 'N', 'B', 'w', 0x05, 0x00, 0xbf, 0x00, 0x00, 0x00
    };

    const XnbHeader header = ParseBytes(bytes);

    EXPECT_EQ(header.platform, 'w');
    EXPECT_EQ(header.version, 5);
    EXPECT_EQ(header.compression, XnbCompression::None);
    EXPECT_EQ(header.totalLength, 191);
}

TEST(XnbHeaderTest, LzxCompressedFlagBitIsDetected)
{
    const std::vector<uint8_t> bytes{
        'X', 'N', 'B', 'w', 0x05, 0x80, 0x10, 0x00, 0x00, 0x00
    };

    const XnbHeader header = ParseBytes(bytes);

    EXPECT_EQ(header.compression, XnbCompression::Lzx);
}

TEST(XnbHeaderTest, Lz4CompressedFlagBitIsDetected)
{
    // plan_xnb.md XNB-27: flags bit 0x40, confirmed against MonoGame's own ContentManager.cs
    // (ContentCompressedLz4 = 0x40) -- FNA itself never produces this, but MonoGame's content
    // pipeline can.
    const std::vector<uint8_t> bytes{
        'X', 'N', 'B', 'd', 0x05, 0x40, 0x10, 0x00, 0x00, 0x00
    };

    const XnbHeader header = ParseBytes(bytes);

    EXPECT_EQ(header.compression, XnbCompression::Lz4);
}

TEST(XnbHeaderTest, BothCompressionBitsSetIsUnknown)
{
    const std::vector<uint8_t> bytes{
        'X', 'N', 'B', 'w', 0x05, 0xC0, 0x10, 0x00, 0x00, 0x00
    };

    const XnbHeader header = ParseBytes(bytes);

    EXPECT_EQ(header.compression, XnbCompression::Unknown);
}

TEST(XnbHeaderTest, Version4IsAccepted)
{
    const std::vector<uint8_t> bytes{
        'X', 'N', 'B', 'd', 0x04, 0x00, 0x0a, 0x00, 0x00, 0x00
    };

    const XnbHeader header = ParseBytes(bytes);

    EXPECT_EQ(header.version, 4);
    EXPECT_EQ(header.platform, 'd');
}

TEST(XnbHeaderTest, EveryAcceptedPlatformParses)
{
    for (const char platform : CNA::Internal::Xnb::XnbAcceptedPlatforms())
    {
        const std::vector<uint8_t> bytes{
            'X', 'N', 'B', static_cast<uint8_t>(platform), 0x05, 0x00, 0x0a, 0x00, 0x00, 0x00
        };
        const XnbHeader header = ParseBytes(bytes);
        EXPECT_EQ(header.platform, platform);
    }
}

TEST(XnbHeaderTest, BadMagicBytesThrowsContentLoadException)
{
    const std::vector<uint8_t> bytes{
        'X', 'N', 'X', 'w', 0x05, 0x00, 0x0a, 0x00, 0x00, 0x00
    };

    EXPECT_THROW(ParseBytes(bytes), ContentLoadException);
}

TEST(XnbHeaderTest, UnrecognizedPlatformThrowsContentLoadException)
{
    const std::vector<uint8_t> bytes{
        'X', 'N', 'B', 'Z', 0x05, 0x00, 0x0a, 0x00, 0x00, 0x00
    };

    EXPECT_THROW(ParseBytes(bytes), ContentLoadException);
}

// plan_xnb.md XNB-44: 'b' (WebAssembly/Bridge.NET) is a real platform identifier MonoGame's own
// ContentWriter.targetPlatformIdentifiers accepts, added after FNA's fork point -- FNA's own
// targetPlatformIdentifiers (src/Content/ContentManager.cs) never gained it. CNA's
// XnbAcceptedPlatforms() deliberately matches FNA, not MonoGame's expanded list, so a real
// MonoGame-for-WebAssembly-produced .xnb is correctly rejected rather than silently mishandled --
// confirmed empirically against a real, independently-produced 'b'-platform fixture during this
// session's compatibility sweep (not vendored here: no reader-logic path is actually exercised by
// a rejected platform byte, so a hand-crafted header is equally conclusive and avoids a large,
// low-marginal-value binary in the repo).
TEST(XnbHeaderTest, MonoGameWebAssemblyPlatformIsNotAcceptedMatchingFnaExactly)
{
    const std::vector<uint8_t> bytes{
        'X', 'N', 'B', 'b', 0x05, 0x00, 0x0a, 0x00, 0x00, 0x00
    };

    EXPECT_THROW(ParseBytes(bytes), ContentLoadException);
}

TEST(XnbHeaderTest, InvalidVersionThrowsContentLoadException)
{
    const std::vector<uint8_t> bytes{
        'X', 'N', 'B', 'w', 0x06, 0x00, 0x0a, 0x00, 0x00, 0x00
    };

    EXPECT_THROW(ParseBytes(bytes), ContentLoadException);
}

TEST(XnbHeaderTest, TruncatedHeaderThrowsEndOfStreamException)
{
    const std::vector<uint8_t> bytes{'X', 'N', 'B'}; // missing platform byte onward

    EXPECT_THROW(ParseBytes(bytes), System::IO::EndOfStreamException);
}
