// SPDX-License-Identifier: MS-PL
// AUTO-GENERATED by extract_shader_registers.py -- do not edit by hand.
//
// plan_dx9.md D9-72: the real, compiler-verified constant register layout for each of
// the 66 compiled Stock Effect shaders, extracted from D3DDisassemble()'s own
// "// Registers:" comment block -- NOT hand-derived from the .fx files' _vs(cN)/
// _ps(cN) source annotations. Those source annotations give the STARTING register
// correctly but NOT always the correct register COUNT: a real check found
// EnvironmentMapEffect.fx's World constant (declared float4x4, naively 4 registers)
// is allocated only 3 registers by the real compiler in VSEnvMap specifically, because
// that entry point never reads pos_ws.w -- register occupancy depends on what a given
// ENTRY POINT actually reads, not just a constant's declared HLSL type. Re-run this
// script (not hand-edit) after any vendored .fx change or compile-flag change.
#pragma once
#include <cstdint>

namespace CNA::Internal::Backends::D3D9::Shaders {

/// One named HLSL constant's real register slot within a single compiled shader.
/// `space` is 'v' for a vs_2_0 constant register (SetVertexShaderConstantF) or 'p' for
/// a ps_2_0 one (SetPixelShaderConstantF) -- never both; D3D9 vertex and pixel shader
/// constant register files are entirely independent address spaces.
struct D3D9ShaderConstantSlot
{
    const char* name;
    char space;
    uint8_t registerIndex;
    uint8_t registerCount;
};

static constexpr D3D9ShaderConstantSlot kBasicEffect_VSBasic_Registers[] = {
    {"DiffuseColor", 'v', 0, 1},
    {"FogVector", 'v', 14, 1},
    {"WorldViewProj", 'v', 15, 4}
};

static constexpr D3D9ShaderConstantSlot kBasicEffect_VSBasicNoFog_Registers[] = {
    {"DiffuseColor", 'v', 0, 1},
    {"WorldViewProj", 'v', 15, 4}
};

static constexpr D3D9ShaderConstantSlot kBasicEffect_VSBasicVc_Registers[] = {
    {"DiffuseColor", 'v', 0, 1},
    {"FogVector", 'v', 14, 1},
    {"WorldViewProj", 'v', 15, 4}
};

static constexpr D3D9ShaderConstantSlot kBasicEffect_VSBasicVcNoFog_Registers[] = {
    {"DiffuseColor", 'v', 0, 1},
    {"WorldViewProj", 'v', 15, 4}
};

static constexpr D3D9ShaderConstantSlot kBasicEffect_VSBasicTx_Registers[] = {
    {"DiffuseColor", 'v', 0, 1},
    {"FogVector", 'v', 14, 1},
    {"WorldViewProj", 'v', 15, 4}
};

static constexpr D3D9ShaderConstantSlot kBasicEffect_VSBasicTxNoFog_Registers[] = {
    {"DiffuseColor", 'v', 0, 1},
    {"WorldViewProj", 'v', 15, 4}
};

static constexpr D3D9ShaderConstantSlot kBasicEffect_VSBasicTxVc_Registers[] = {
    {"DiffuseColor", 'v', 0, 1},
    {"FogVector", 'v', 14, 1},
    {"WorldViewProj", 'v', 15, 4}
};

static constexpr D3D9ShaderConstantSlot kBasicEffect_VSBasicTxVcNoFog_Registers[] = {
    {"DiffuseColor", 'v', 0, 1},
    {"WorldViewProj", 'v', 15, 4}
};

static constexpr D3D9ShaderConstantSlot kBasicEffect_VSBasicVertexLighting_Registers[] = {
    {"DiffuseColor", 'v', 0, 1},
    {"EmissiveColor", 'v', 1, 1},
    {"SpecularColor", 'v', 2, 1},
    {"SpecularPower", 'v', 3, 1},
    {"DirLight0Direction", 'v', 4, 1},
    {"DirLight0DiffuseColor", 'v', 5, 1},
    {"DirLight0SpecularColor", 'v', 6, 1},
    {"DirLight1Direction", 'v', 7, 1},
    {"DirLight1DiffuseColor", 'v', 8, 1},
    {"DirLight1SpecularColor", 'v', 9, 1},
    {"DirLight2Direction", 'v', 10, 1},
    {"DirLight2DiffuseColor", 'v', 11, 1},
    {"DirLight2SpecularColor", 'v', 12, 1},
    {"EyePosition", 'v', 13, 1},
    {"FogVector", 'v', 14, 1},
    {"WorldViewProj", 'v', 15, 4},
    {"World", 'v', 19, 3},
    {"WorldInverseTranspose", 'v', 23, 3}
};

static constexpr D3D9ShaderConstantSlot kBasicEffect_VSBasicVertexLightingVc_Registers[] = {
    {"DiffuseColor", 'v', 0, 1},
    {"EmissiveColor", 'v', 1, 1},
    {"SpecularColor", 'v', 2, 1},
    {"SpecularPower", 'v', 3, 1},
    {"DirLight0Direction", 'v', 4, 1},
    {"DirLight0DiffuseColor", 'v', 5, 1},
    {"DirLight0SpecularColor", 'v', 6, 1},
    {"DirLight1Direction", 'v', 7, 1},
    {"DirLight1DiffuseColor", 'v', 8, 1},
    {"DirLight1SpecularColor", 'v', 9, 1},
    {"DirLight2Direction", 'v', 10, 1},
    {"DirLight2DiffuseColor", 'v', 11, 1},
    {"DirLight2SpecularColor", 'v', 12, 1},
    {"EyePosition", 'v', 13, 1},
    {"FogVector", 'v', 14, 1},
    {"WorldViewProj", 'v', 15, 4},
    {"World", 'v', 19, 3},
    {"WorldInverseTranspose", 'v', 23, 3}
};

static constexpr D3D9ShaderConstantSlot kBasicEffect_VSBasicVertexLightingTx_Registers[] = {
    {"DiffuseColor", 'v', 0, 1},
    {"EmissiveColor", 'v', 1, 1},
    {"SpecularColor", 'v', 2, 1},
    {"SpecularPower", 'v', 3, 1},
    {"DirLight0Direction", 'v', 4, 1},
    {"DirLight0DiffuseColor", 'v', 5, 1},
    {"DirLight0SpecularColor", 'v', 6, 1},
    {"DirLight1Direction", 'v', 7, 1},
    {"DirLight1DiffuseColor", 'v', 8, 1},
    {"DirLight1SpecularColor", 'v', 9, 1},
    {"DirLight2Direction", 'v', 10, 1},
    {"DirLight2DiffuseColor", 'v', 11, 1},
    {"DirLight2SpecularColor", 'v', 12, 1},
    {"EyePosition", 'v', 13, 1},
    {"FogVector", 'v', 14, 1},
    {"WorldViewProj", 'v', 15, 4},
    {"World", 'v', 19, 3},
    {"WorldInverseTranspose", 'v', 23, 3}
};

static constexpr D3D9ShaderConstantSlot kBasicEffect_VSBasicVertexLightingTxVc_Registers[] = {
    {"DiffuseColor", 'v', 0, 1},
    {"EmissiveColor", 'v', 1, 1},
    {"SpecularColor", 'v', 2, 1},
    {"SpecularPower", 'v', 3, 1},
    {"DirLight0Direction", 'v', 4, 1},
    {"DirLight0DiffuseColor", 'v', 5, 1},
    {"DirLight0SpecularColor", 'v', 6, 1},
    {"DirLight1Direction", 'v', 7, 1},
    {"DirLight1DiffuseColor", 'v', 8, 1},
    {"DirLight1SpecularColor", 'v', 9, 1},
    {"DirLight2Direction", 'v', 10, 1},
    {"DirLight2DiffuseColor", 'v', 11, 1},
    {"DirLight2SpecularColor", 'v', 12, 1},
    {"EyePosition", 'v', 13, 1},
    {"FogVector", 'v', 14, 1},
    {"WorldViewProj", 'v', 15, 4},
    {"World", 'v', 19, 3},
    {"WorldInverseTranspose", 'v', 23, 3}
};

static constexpr D3D9ShaderConstantSlot kBasicEffect_VSBasicOneLight_Registers[] = {
    {"DiffuseColor", 'v', 0, 1},
    {"EmissiveColor", 'v', 1, 1},
    {"SpecularColor", 'v', 2, 1},
    {"SpecularPower", 'v', 3, 1},
    {"DirLight0Direction", 'v', 4, 1},
    {"DirLight0DiffuseColor", 'v', 5, 1},
    {"DirLight0SpecularColor", 'v', 6, 1},
    {"EyePosition", 'v', 13, 1},
    {"FogVector", 'v', 14, 1},
    {"WorldViewProj", 'v', 15, 4},
    {"World", 'v', 19, 3},
    {"WorldInverseTranspose", 'v', 23, 3}
};

static constexpr D3D9ShaderConstantSlot kBasicEffect_VSBasicOneLightVc_Registers[] = {
    {"DiffuseColor", 'v', 0, 1},
    {"EmissiveColor", 'v', 1, 1},
    {"SpecularColor", 'v', 2, 1},
    {"SpecularPower", 'v', 3, 1},
    {"DirLight0Direction", 'v', 4, 1},
    {"DirLight0DiffuseColor", 'v', 5, 1},
    {"DirLight0SpecularColor", 'v', 6, 1},
    {"EyePosition", 'v', 13, 1},
    {"FogVector", 'v', 14, 1},
    {"WorldViewProj", 'v', 15, 4},
    {"World", 'v', 19, 3},
    {"WorldInverseTranspose", 'v', 23, 3}
};

static constexpr D3D9ShaderConstantSlot kBasicEffect_VSBasicOneLightTx_Registers[] = {
    {"DiffuseColor", 'v', 0, 1},
    {"EmissiveColor", 'v', 1, 1},
    {"SpecularColor", 'v', 2, 1},
    {"SpecularPower", 'v', 3, 1},
    {"DirLight0Direction", 'v', 4, 1},
    {"DirLight0DiffuseColor", 'v', 5, 1},
    {"DirLight0SpecularColor", 'v', 6, 1},
    {"EyePosition", 'v', 13, 1},
    {"FogVector", 'v', 14, 1},
    {"WorldViewProj", 'v', 15, 4},
    {"World", 'v', 19, 3},
    {"WorldInverseTranspose", 'v', 23, 3}
};

static constexpr D3D9ShaderConstantSlot kBasicEffect_VSBasicOneLightTxVc_Registers[] = {
    {"DiffuseColor", 'v', 0, 1},
    {"EmissiveColor", 'v', 1, 1},
    {"SpecularColor", 'v', 2, 1},
    {"SpecularPower", 'v', 3, 1},
    {"DirLight0Direction", 'v', 4, 1},
    {"DirLight0DiffuseColor", 'v', 5, 1},
    {"DirLight0SpecularColor", 'v', 6, 1},
    {"EyePosition", 'v', 13, 1},
    {"FogVector", 'v', 14, 1},
    {"WorldViewProj", 'v', 15, 4},
    {"World", 'v', 19, 3},
    {"WorldInverseTranspose", 'v', 23, 3}
};

static constexpr D3D9ShaderConstantSlot kBasicEffect_VSBasicPixelLighting_Registers[] = {
    {"DiffuseColor", 'v', 0, 1},
    {"FogVector", 'v', 14, 1},
    {"WorldViewProj", 'v', 15, 4},
    {"World", 'v', 19, 3},
    {"WorldInverseTranspose", 'v', 23, 3}
};

static constexpr D3D9ShaderConstantSlot kBasicEffect_VSBasicPixelLightingVc_Registers[] = {
    {"DiffuseColor", 'v', 0, 1},
    {"FogVector", 'v', 14, 1},
    {"WorldViewProj", 'v', 15, 4},
    {"World", 'v', 19, 3},
    {"WorldInverseTranspose", 'v', 23, 3}
};

static constexpr D3D9ShaderConstantSlot kBasicEffect_VSBasicPixelLightingTx_Registers[] = {
    {"DiffuseColor", 'v', 0, 1},
    {"FogVector", 'v', 14, 1},
    {"WorldViewProj", 'v', 15, 4},
    {"World", 'v', 19, 3},
    {"WorldInverseTranspose", 'v', 23, 3}
};

static constexpr D3D9ShaderConstantSlot kBasicEffect_VSBasicPixelLightingTxVc_Registers[] = {
    {"DiffuseColor", 'v', 0, 1},
    {"FogVector", 'v', 14, 1},
    {"WorldViewProj", 'v', 15, 4},
    {"World", 'v', 19, 3},
    {"WorldInverseTranspose", 'v', 23, 3}
};

static constexpr D3D9ShaderConstantSlot kBasicEffect_PSBasic_Registers[] = {
    {"FogColor", 'p', 0, 1}
};

static constexpr D3D9ShaderConstantSlot* kBasicEffect_PSBasicNoFog_Registers = nullptr; // no named constants

static constexpr D3D9ShaderConstantSlot kBasicEffect_PSBasicTx_Registers[] = {
    {"FogColor", 'p', 0, 1}
};

static constexpr D3D9ShaderConstantSlot* kBasicEffect_PSBasicTxNoFog_Registers = nullptr; // no named constants

static constexpr D3D9ShaderConstantSlot kBasicEffect_PSBasicVertexLighting_Registers[] = {
    {"FogColor", 'p', 0, 1}
};

static constexpr D3D9ShaderConstantSlot* kBasicEffect_PSBasicVertexLightingNoFog_Registers = nullptr; // no named constants

static constexpr D3D9ShaderConstantSlot kBasicEffect_PSBasicVertexLightingTx_Registers[] = {
    {"FogColor", 'p', 0, 1}
};

static constexpr D3D9ShaderConstantSlot* kBasicEffect_PSBasicVertexLightingTxNoFog_Registers = nullptr; // no named constants

static constexpr D3D9ShaderConstantSlot kBasicEffect_PSBasicPixelLighting_Registers[] = {
    {"FogColor", 'p', 0, 1},
    {"DiffuseColor", 'p', 1, 1},
    {"EmissiveColor", 'p', 2, 1},
    {"SpecularColor", 'p', 3, 1},
    {"SpecularPower", 'p', 4, 1},
    {"DirLight0Direction", 'p', 5, 1},
    {"DirLight0DiffuseColor", 'p', 6, 1},
    {"DirLight0SpecularColor", 'p', 7, 1},
    {"DirLight1Direction", 'p', 8, 1},
    {"DirLight1DiffuseColor", 'p', 9, 1},
    {"DirLight1SpecularColor", 'p', 10, 1},
    {"DirLight2Direction", 'p', 11, 1},
    {"DirLight2DiffuseColor", 'p', 12, 1},
    {"DirLight2SpecularColor", 'p', 13, 1},
    {"EyePosition", 'p', 14, 1}
};

static constexpr D3D9ShaderConstantSlot kBasicEffect_PSBasicPixelLightingTx_Registers[] = {
    {"FogColor", 'p', 0, 1},
    {"DiffuseColor", 'p', 1, 1},
    {"EmissiveColor", 'p', 2, 1},
    {"SpecularColor", 'p', 3, 1},
    {"SpecularPower", 'p', 4, 1},
    {"DirLight0Direction", 'p', 5, 1},
    {"DirLight0DiffuseColor", 'p', 6, 1},
    {"DirLight0SpecularColor", 'p', 7, 1},
    {"DirLight1Direction", 'p', 8, 1},
    {"DirLight1DiffuseColor", 'p', 9, 1},
    {"DirLight1SpecularColor", 'p', 10, 1},
    {"DirLight2Direction", 'p', 11, 1},
    {"DirLight2DiffuseColor", 'p', 12, 1},
    {"DirLight2SpecularColor", 'p', 13, 1},
    {"EyePosition", 'p', 14, 1}
};

static constexpr D3D9ShaderConstantSlot kAlphaTestEffect_VSAlphaTest_Registers[] = {
    {"DiffuseColor", 'v', 0, 1},
    {"WorldViewProj", 'v', 1, 4},
    {"FogVector", 'v', 5, 1}
};

static constexpr D3D9ShaderConstantSlot kAlphaTestEffect_VSAlphaTestNoFog_Registers[] = {
    {"DiffuseColor", 'v', 0, 1},
    {"WorldViewProj", 'v', 1, 4}
};

static constexpr D3D9ShaderConstantSlot kAlphaTestEffect_VSAlphaTestVc_Registers[] = {
    {"DiffuseColor", 'v', 0, 1},
    {"WorldViewProj", 'v', 1, 4},
    {"FogVector", 'v', 5, 1}
};

static constexpr D3D9ShaderConstantSlot kAlphaTestEffect_VSAlphaTestVcNoFog_Registers[] = {
    {"DiffuseColor", 'v', 0, 1},
    {"WorldViewProj", 'v', 1, 4}
};

static constexpr D3D9ShaderConstantSlot kAlphaTestEffect_PSAlphaTestLtGt_Registers[] = {
    {"AlphaTest", 'p', 0, 1},
    {"FogColor", 'p', 1, 1}
};

static constexpr D3D9ShaderConstantSlot kAlphaTestEffect_PSAlphaTestLtGtNoFog_Registers[] = {
    {"AlphaTest", 'p', 0, 1}
};

static constexpr D3D9ShaderConstantSlot kAlphaTestEffect_PSAlphaTestEqNe_Registers[] = {
    {"AlphaTest", 'p', 0, 1},
    {"FogColor", 'p', 1, 1}
};

static constexpr D3D9ShaderConstantSlot kAlphaTestEffect_PSAlphaTestEqNeNoFog_Registers[] = {
    {"AlphaTest", 'p', 0, 1}
};

static constexpr D3D9ShaderConstantSlot kDualTextureEffect_VSDualTexture_Registers[] = {
    {"DiffuseColor", 'v', 0, 1},
    {"WorldViewProj", 'v', 1, 4},
    {"FogVector", 'v', 5, 1}
};

static constexpr D3D9ShaderConstantSlot kDualTextureEffect_VSDualTextureNoFog_Registers[] = {
    {"DiffuseColor", 'v', 0, 1},
    {"WorldViewProj", 'v', 1, 4}
};

static constexpr D3D9ShaderConstantSlot kDualTextureEffect_VSDualTextureVc_Registers[] = {
    {"DiffuseColor", 'v', 0, 1},
    {"WorldViewProj", 'v', 1, 4},
    {"FogVector", 'v', 5, 1}
};

static constexpr D3D9ShaderConstantSlot kDualTextureEffect_VSDualTextureVcNoFog_Registers[] = {
    {"DiffuseColor", 'v', 0, 1},
    {"WorldViewProj", 'v', 1, 4}
};

static constexpr D3D9ShaderConstantSlot kDualTextureEffect_PSDualTexture_Registers[] = {
    {"FogColor", 'p', 0, 1}
};

static constexpr D3D9ShaderConstantSlot* kDualTextureEffect_PSDualTextureNoFog_Registers = nullptr; // no named constants

static constexpr D3D9ShaderConstantSlot kEnvironmentMapEffect_VSEnvMap_Registers[] = {
    {"EnvironmentMapAmount", 'v', 1, 1},
    {"DiffuseColor", 'v', 2, 1},
    {"EmissiveColor", 'v', 3, 1},
    {"DirLight0Direction", 'v', 4, 1},
    {"DirLight0DiffuseColor", 'v', 5, 1},
    {"DirLight1Direction", 'v', 6, 1},
    {"DirLight1DiffuseColor", 'v', 7, 1},
    {"DirLight2Direction", 'v', 8, 1},
    {"DirLight2DiffuseColor", 'v', 9, 1},
    {"EyePosition", 'v', 10, 1},
    {"FogVector", 'v', 11, 1},
    {"WorldViewProj", 'v', 12, 4},
    {"World", 'v', 16, 3},
    {"WorldInverseTranspose", 'v', 19, 3}
};

static constexpr D3D9ShaderConstantSlot kEnvironmentMapEffect_VSEnvMapFresnel_Registers[] = {
    {"FresnelFactor", 'v', 0, 1},
    {"EnvironmentMapAmount", 'v', 1, 1},
    {"DiffuseColor", 'v', 2, 1},
    {"EmissiveColor", 'v', 3, 1},
    {"DirLight0Direction", 'v', 4, 1},
    {"DirLight0DiffuseColor", 'v', 5, 1},
    {"DirLight1Direction", 'v', 6, 1},
    {"DirLight1DiffuseColor", 'v', 7, 1},
    {"DirLight2Direction", 'v', 8, 1},
    {"DirLight2DiffuseColor", 'v', 9, 1},
    {"EyePosition", 'v', 10, 1},
    {"FogVector", 'v', 11, 1},
    {"WorldViewProj", 'v', 12, 4},
    {"World", 'v', 16, 3},
    {"WorldInverseTranspose", 'v', 19, 3}
};

static constexpr D3D9ShaderConstantSlot kEnvironmentMapEffect_VSEnvMapOneLight_Registers[] = {
    {"EnvironmentMapAmount", 'v', 1, 1},
    {"DiffuseColor", 'v', 2, 1},
    {"EmissiveColor", 'v', 3, 1},
    {"DirLight0Direction", 'v', 4, 1},
    {"DirLight0DiffuseColor", 'v', 5, 1},
    {"EyePosition", 'v', 10, 1},
    {"FogVector", 'v', 11, 1},
    {"WorldViewProj", 'v', 12, 4},
    {"World", 'v', 16, 3},
    {"WorldInverseTranspose", 'v', 19, 3}
};

static constexpr D3D9ShaderConstantSlot kEnvironmentMapEffect_VSEnvMapOneLightFresnel_Registers[] = {
    {"FresnelFactor", 'v', 0, 1},
    {"EnvironmentMapAmount", 'v', 1, 1},
    {"DiffuseColor", 'v', 2, 1},
    {"EmissiveColor", 'v', 3, 1},
    {"DirLight0Direction", 'v', 4, 1},
    {"DirLight0DiffuseColor", 'v', 5, 1},
    {"EyePosition", 'v', 10, 1},
    {"FogVector", 'v', 11, 1},
    {"WorldViewProj", 'v', 12, 4},
    {"World", 'v', 16, 3},
    {"WorldInverseTranspose", 'v', 19, 3}
};

static constexpr D3D9ShaderConstantSlot kEnvironmentMapEffect_PSEnvMap_Registers[] = {
    {"FogColor", 'p', 1, 1}
};

static constexpr D3D9ShaderConstantSlot* kEnvironmentMapEffect_PSEnvMapNoFog_Registers = nullptr; // no named constants

static constexpr D3D9ShaderConstantSlot kEnvironmentMapEffect_PSEnvMapSpecular_Registers[] = {
    {"EnvironmentMapSpecular", 'p', 0, 1},
    {"FogColor", 'p', 1, 1}
};

static constexpr D3D9ShaderConstantSlot kEnvironmentMapEffect_PSEnvMapSpecularNoFog_Registers[] = {
    {"EnvironmentMapSpecular", 'p', 0, 1}
};

static constexpr D3D9ShaderConstantSlot kSkinnedEffect_VSSkinnedVertexLightingOneBone_Registers[] = {
    {"DiffuseColor", 'v', 0, 1},
    {"EmissiveColor", 'v', 1, 1},
    {"SpecularColor", 'v', 2, 1},
    {"SpecularPower", 'v', 3, 1},
    {"DirLight0Direction", 'v', 4, 1},
    {"DirLight0DiffuseColor", 'v', 5, 1},
    {"DirLight0SpecularColor", 'v', 6, 1},
    {"DirLight1Direction", 'v', 7, 1},
    {"DirLight1DiffuseColor", 'v', 8, 1},
    {"DirLight1SpecularColor", 'v', 9, 1},
    {"DirLight2Direction", 'v', 10, 1},
    {"DirLight2DiffuseColor", 'v', 11, 1},
    {"DirLight2SpecularColor", 'v', 12, 1},
    {"EyePosition", 'v', 13, 1},
    {"FogVector", 'v', 14, 1},
    {"WorldViewProj", 'v', 15, 4},
    {"World", 'v', 19, 3},
    {"WorldInverseTranspose", 'v', 23, 3},
    {"Bones", 'v', 26, 216}
};

static constexpr D3D9ShaderConstantSlot kSkinnedEffect_VSSkinnedVertexLightingTwoBones_Registers[] = {
    {"DiffuseColor", 'v', 0, 1},
    {"EmissiveColor", 'v', 1, 1},
    {"SpecularColor", 'v', 2, 1},
    {"SpecularPower", 'v', 3, 1},
    {"DirLight0Direction", 'v', 4, 1},
    {"DirLight0DiffuseColor", 'v', 5, 1},
    {"DirLight0SpecularColor", 'v', 6, 1},
    {"DirLight1Direction", 'v', 7, 1},
    {"DirLight1DiffuseColor", 'v', 8, 1},
    {"DirLight1SpecularColor", 'v', 9, 1},
    {"DirLight2Direction", 'v', 10, 1},
    {"DirLight2DiffuseColor", 'v', 11, 1},
    {"DirLight2SpecularColor", 'v', 12, 1},
    {"EyePosition", 'v', 13, 1},
    {"FogVector", 'v', 14, 1},
    {"WorldViewProj", 'v', 15, 4},
    {"World", 'v', 19, 3},
    {"WorldInverseTranspose", 'v', 23, 3},
    {"Bones", 'v', 26, 216}
};

static constexpr D3D9ShaderConstantSlot kSkinnedEffect_VSSkinnedVertexLightingFourBones_Registers[] = {
    {"DiffuseColor", 'v', 0, 1},
    {"EmissiveColor", 'v', 1, 1},
    {"SpecularColor", 'v', 2, 1},
    {"SpecularPower", 'v', 3, 1},
    {"DirLight0Direction", 'v', 4, 1},
    {"DirLight0DiffuseColor", 'v', 5, 1},
    {"DirLight0SpecularColor", 'v', 6, 1},
    {"DirLight1Direction", 'v', 7, 1},
    {"DirLight1DiffuseColor", 'v', 8, 1},
    {"DirLight1SpecularColor", 'v', 9, 1},
    {"DirLight2Direction", 'v', 10, 1},
    {"DirLight2DiffuseColor", 'v', 11, 1},
    {"DirLight2SpecularColor", 'v', 12, 1},
    {"EyePosition", 'v', 13, 1},
    {"FogVector", 'v', 14, 1},
    {"WorldViewProj", 'v', 15, 4},
    {"World", 'v', 19, 3},
    {"WorldInverseTranspose", 'v', 23, 3},
    {"Bones", 'v', 26, 216}
};

static constexpr D3D9ShaderConstantSlot kSkinnedEffect_VSSkinnedOneLightOneBone_Registers[] = {
    {"DiffuseColor", 'v', 0, 1},
    {"EmissiveColor", 'v', 1, 1},
    {"SpecularColor", 'v', 2, 1},
    {"SpecularPower", 'v', 3, 1},
    {"DirLight0Direction", 'v', 4, 1},
    {"DirLight0DiffuseColor", 'v', 5, 1},
    {"DirLight0SpecularColor", 'v', 6, 1},
    {"EyePosition", 'v', 13, 1},
    {"FogVector", 'v', 14, 1},
    {"WorldViewProj", 'v', 15, 4},
    {"World", 'v', 19, 3},
    {"WorldInverseTranspose", 'v', 23, 3},
    {"Bones", 'v', 26, 216}
};

static constexpr D3D9ShaderConstantSlot kSkinnedEffect_VSSkinnedOneLightTwoBones_Registers[] = {
    {"DiffuseColor", 'v', 0, 1},
    {"EmissiveColor", 'v', 1, 1},
    {"SpecularColor", 'v', 2, 1},
    {"SpecularPower", 'v', 3, 1},
    {"DirLight0Direction", 'v', 4, 1},
    {"DirLight0DiffuseColor", 'v', 5, 1},
    {"DirLight0SpecularColor", 'v', 6, 1},
    {"EyePosition", 'v', 13, 1},
    {"FogVector", 'v', 14, 1},
    {"WorldViewProj", 'v', 15, 4},
    {"World", 'v', 19, 3},
    {"WorldInverseTranspose", 'v', 23, 3},
    {"Bones", 'v', 26, 216}
};

static constexpr D3D9ShaderConstantSlot kSkinnedEffect_VSSkinnedOneLightFourBones_Registers[] = {
    {"DiffuseColor", 'v', 0, 1},
    {"EmissiveColor", 'v', 1, 1},
    {"SpecularColor", 'v', 2, 1},
    {"SpecularPower", 'v', 3, 1},
    {"DirLight0Direction", 'v', 4, 1},
    {"DirLight0DiffuseColor", 'v', 5, 1},
    {"DirLight0SpecularColor", 'v', 6, 1},
    {"EyePosition", 'v', 13, 1},
    {"FogVector", 'v', 14, 1},
    {"WorldViewProj", 'v', 15, 4},
    {"World", 'v', 19, 3},
    {"WorldInverseTranspose", 'v', 23, 3},
    {"Bones", 'v', 26, 216}
};

static constexpr D3D9ShaderConstantSlot kSkinnedEffect_VSSkinnedPixelLightingOneBone_Registers[] = {
    {"DiffuseColor", 'v', 0, 1},
    {"FogVector", 'v', 14, 1},
    {"WorldViewProj", 'v', 15, 4},
    {"World", 'v', 19, 3},
    {"WorldInverseTranspose", 'v', 23, 3},
    {"Bones", 'v', 26, 216}
};

static constexpr D3D9ShaderConstantSlot kSkinnedEffect_VSSkinnedPixelLightingTwoBones_Registers[] = {
    {"DiffuseColor", 'v', 0, 1},
    {"FogVector", 'v', 14, 1},
    {"WorldViewProj", 'v', 15, 4},
    {"World", 'v', 19, 3},
    {"WorldInverseTranspose", 'v', 23, 3},
    {"Bones", 'v', 26, 216}
};

static constexpr D3D9ShaderConstantSlot kSkinnedEffect_VSSkinnedPixelLightingFourBones_Registers[] = {
    {"DiffuseColor", 'v', 0, 1},
    {"FogVector", 'v', 14, 1},
    {"WorldViewProj", 'v', 15, 4},
    {"World", 'v', 19, 3},
    {"WorldInverseTranspose", 'v', 23, 3},
    {"Bones", 'v', 26, 216}
};

static constexpr D3D9ShaderConstantSlot kSkinnedEffect_PSSkinnedVertexLighting_Registers[] = {
    {"FogColor", 'p', 0, 1}
};

static constexpr D3D9ShaderConstantSlot* kSkinnedEffect_PSSkinnedVertexLightingNoFog_Registers = nullptr; // no named constants

static constexpr D3D9ShaderConstantSlot kSkinnedEffect_PSSkinnedPixelLighting_Registers[] = {
    {"FogColor", 'p', 0, 1},
    {"DiffuseColor", 'p', 1, 1},
    {"EmissiveColor", 'p', 2, 1},
    {"SpecularColor", 'p', 3, 1},
    {"SpecularPower", 'p', 4, 1},
    {"DirLight0Direction", 'p', 5, 1},
    {"DirLight0DiffuseColor", 'p', 6, 1},
    {"DirLight0SpecularColor", 'p', 7, 1},
    {"DirLight1Direction", 'p', 8, 1},
    {"DirLight1DiffuseColor", 'p', 9, 1},
    {"DirLight1SpecularColor", 'p', 10, 1},
    {"DirLight2Direction", 'p', 11, 1},
    {"DirLight2DiffuseColor", 'p', 12, 1},
    {"DirLight2SpecularColor", 'p', 13, 1},
    {"EyePosition", 'p', 14, 1}
};

static constexpr D3D9ShaderConstantSlot kSpriteEffect_SpriteVertexShader_Registers[] = {
    {"MatrixTransform", 'v', 0, 4}
};

static constexpr D3D9ShaderConstantSlot* kSpriteEffect_SpritePixelShader_Registers = nullptr; // no named constants

} // namespace CNA::Internal::Backends::D3D9::Shaders
